=== dhadotid/Cari-Ilmu/xml/toko.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="root" type="dt_toko"></xs:element>
    <xs:complexType name="dt_toko">
        <xs:sequence>
            <xs:element name="toko" type="store" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="store">
        <xs:sequence>
            <xs:element name="img" type="xs:string"></xs:element>
            <xs:element name="store_name" type="xs:string"></xs:element>
            <xs:element name="phonenumber" type="noP"></xs:element>
        </xs:sequence>
        <xs:attribute name="id_store" type="strID" use="required"></xs:attribute>
    </xs:complexType>
    <xs:simpleType name="strID">
        <xs:restriction base="xs:string">
            <xs:pattern value="S[0-9][0-9][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="noP">
        <xs:restriction base="xs:string">
            <xs:pattern value="[+]62[0-9]{9,12}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== dhadotid/Cari-Ilmu/xml/toko.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="toko.xsd">
    <toko id_store="S001">
        <img>img/gramedia.png</img>
        <store_name>Gramedia</store_name>
        <phonenumber>+628227780827</phonenumber>
    </toko>
    <toko id_store="S002">
        <img>img/periplus.png</img>
        <store_name>Periplus</store_name>
        <phonenumber>+62822770822</phonenumber>
    </toko>
    <toko id_store="S003">
        <img>img/aksara.jpg</img>
        <store_name>Aksara</store_name>
        <phonenumber>+62823340851</phonenumber>
    </toko>
    <toko id_store="S004">
        <img>img/karisma.png</img>
        <store_name>Karisma</store_name>
        <phonenumber>+628227288647</phonenumber>
    </toko>
</root>
